#!/bin/sh
# inst9

case $# in
1|2)
	;;
*)
	echo "usage: qemu9 img [iso]" 1>&2
	exit 1
	;;
esac

img=$1
iso=$2

qemu="qemu-system-x86_64 -cpu host -smp 4 -enable-kvm -m 4G \
	-net nic,model=virtio,macaddr=52:54:ca:fe:ba:be,netdev=network0 \
	-netdev tap,id=network0,ifname=tap0,script=no,downscript=no \
	-device virtio-scsi-pci,id=scsi \
	-drive if=none,id=vd0,file=$img \
	-device scsi-hd,drive=vd0"

if [ -n "$iso" ]
then
	qemu="$qemu -drive file=$iso,media=disk"
fi

exec $qemu
